name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'runbooks/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
