name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'runbooks/**'

permissions:
  contents: write

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: rymndhng/release-on-push-action@aebba2bbce07a9474bf95e8710e5ee8a9e922fe2  # master
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
