name: runbooks

on:
  schedule:
    - cron: '55 */8 * * *'
  workflow_dispatch:


jobs:
  runbooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
        with:
          token: ${{secrets.PAT}}

      - name: INSTALL - python@3.10
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa  # v4.8.0
        with:
          python-version: '3.10'

      - name: Install guardduty-runbooks
        run: pip install guardduty-runbooks

      - name: Create Runbooks
        run: guardduty-runbooks --outdir ./runbooks --overwrite

      - name: Commit and Push
        run: ./.github/commit-and-push.sh
        env:
          NAME: ${{ secrets.NAME }}
          EMAIL: ${{ secrets.EMAIL }}
